resources:
  - ../../components/flux
  - ../../components/sealed-secrets
  - ../../components/cluster-api
  - ../../components/cluster
  - configmap.yaml
  - credentials-sealed.yaml


# for soda
  - ../../components/soda
# for canfar
  - ../../components/canfar

  - ../../infra

# for Blackbox exporter probe , prometheus and grafana with overlay

  # - ../../infra-prod/overlays/prod
  
# Patch the Helm release for the cluster to update the release name
#   This ensures we get nicely named resources in OpenStack
# We also add our configmap to the values sources for the release
patches:
  - target:
      kind: HelmRelease
      name: cluster
    patch: |-
      - op: replace
        path: /spec/releaseName
        value: bo307-cambridge-cluster-test

      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: cluster-cambridge-config-bo307test
          valuesKey: values.yaml
