    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.128-232-226-7.sslip.io
    posixMapper:
      image:
        repository: images.opencadc.org/platform/posix-mapper
        tag: 0.2.1
        pullPolicy: IfNotPresent
      resourceID:  ivo://camrc.xyz/posix-mapper
      resources:
        requests:
          memory: "500M"
          cpu: "500m"
        limits:
          memory: "500M"
          cpu: "500m"
      minUID: 1000
      minGID: 900000
      registryURL: https://spsrc27.iaa.csic.es/reg

      # Optionally mount a custom CA certificate
      extraVolumeMounts:
      - mountPath: "/config/cacerts"
        name: cacert-volume

      # Create the CA certificate volume to be mounted in extraVolumeMounts
      extraVolumes:
      - name: cacert-volume
        secret:
          defaultMode: 420
          secretName: canfar-tls-secret

    storage:
      service:
        persistentVolumeClaim:
          claimName: skaha-pvc
    # delete this later
    # secrets:
    #   postgresql:
    #     auth:
    #       username: posixmapper
    #       password: posixmapperpwd
    #       database: mapping
    #       schema: mapping
    secrets:
      # secretName: posixmapper-db-secret
    base:
      install: false
