apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: soda-release
  namespace: ska-src-soda
spec:
  chart:
    spec:
      chart: etc/helm
      version: 0.0.1       
      sourceRef:
        kind: GitRepository
        name: soda-repo    
        namespace: ska-src-soda 
  interval: 1h
  values:
    deployment:
      namespace: ska-src-soda
    persistence:
      storageClass: ""  
      existingClaim: ""
      enabled: true
      accessMode: ReadOnlyMany
      size: 10Gi
    image:
      repository: harbor.srcdev.skao.int/soda/visivo-vlkb-soda
      tag: 1.6.2
      pullPolicy: Always
    ingress:
      enabled: true
      # host: soda.camrc.xyz
      host: soda.128-232-226-7.sslip.io
    config:
      datasets: |-
        fits_path_surveys=/srv/soda/datasets
        fits_path_cutouts=/srv/soda/cutouts
        ivoid_authority=test.skao
        ivoid_resource_key=datasets/fits
