apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ska-src-soda
  name: ska-src-soda
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ska-src-soda
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: ska-src-soda
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ska-src-soda
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: "/srv/surveys/ska"
          name: soda-pvc
        - mountPath: "/config/datasets.conf"
          name: datasets-conf
          subPath: datasets.conf
        env:
        {{- range $env_key, $env_val := $.Values.extraEnv }}
          - name: {{ $env_val.name }}
            value: {{ $env_val.value }}
        {{- end }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: soda-pvc
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default "soda-pvc" }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: datasets-conf
          configMap:
            name: datasets.conf

status: {}

