apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: base
  namespace: skaha-system
spec:
  chart: base
  version: "0.3.3"   # Replace with the actual version
  sourceRef:
    kind: HelmRepository
    name: science-platform
  interval: 10m