apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-pvc
  namespace: skaha-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: csi-cinder
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-workload-cavern-pvc
  namespace: skaha-workload
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: csi-cinder
  resources:
    requests:
      storage: 10Gi